FROM nginx:alpine

# Копирование фронтенда
COPY frontend/ /usr/share/nginx/html/

# Копирование конфигурации nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]